import Foundation

public enum AchievementRules {
    public struct DailyGoalTargets: Equatable {
        public let calorieGoal: Double?
        public let protein: Double
        public let carbs: Double
        public let fats: Double

        public init(calorieGoal: Double?, protein: Double, carbs: Double, fats: Double) {
            self.calorieGoal = calorieGoal
            self.protein = protein
            self.carbs = carbs
            self.fats = fats
        }
    }

    public struct DailyGoalEvaluation: Equatable {
        public let calorieHit: Bool
        public let proteinHit: Bool
        public let macroMasterHit: Bool
        public let hydrationHit: Bool

        public init(calorieHit: Bool, proteinHit: Bool, macroMasterHit: Bool, hydrationHit: Bool) {
            self.calorieHit = calorieHit
            self.proteinHit = proteinHit
            self.macroMasterHit = macroMasterHit
            self.hydrationHit = hydrationHit
        }
    }

    public static let defaultLevelThresholds: [Int] = [0, 100, 250, 500, 1000, 2000, 5000]

    public static func defaultDefinitions() -> [AchievementDefinition] {
        [
            AchievementDefinition(id: "first_log", title: "First Steps", description: "Log your first meal or food item.", iconName: "figure.walk.arrival", criteriaType: .loggingStreak, criteriaValue: 1, pointsValue: 10),
            AchievementDefinition(id: "log_streak_3", title: "Getting Started", description: "Log food entries for 3 consecutive days.", iconName: "flame.fill", criteriaType: .loggingStreak, criteriaValue: 3, pointsValue: 20),
            AchievementDefinition(id: "log_streak_7", title: "Consistent Logger", description: "Log food entries for 7 consecutive days.", iconName: "calendar.badge.clock", criteriaType: .loggingStreak, criteriaValue: 7, pointsValue: 50),
            AchievementDefinition(id: "goal_setter", title: "Goal Setter", description: "Set your initial calorie and macro goals.", iconName: "target", criteriaType: .featureUsed, criteriaValue: 1, pointsValue: 15),
            AchievementDefinition(id: "calorie_target_hit", title: "Calorie Target Hit", description: "Meet your daily calorie goal.", iconName: "checkmark.circle.fill", criteriaType: .calorieGoalHitCount, criteriaValue: 1, pointsValue: 20),
            AchievementDefinition(id: "macro_master", title: "Macro Master", description: "Meet all 3 macro goals on the same day.", iconName: "chart.pie.fill", criteriaType: .macroGoalHitCount, criteriaValue: 1, pointsValue: 30),
            AchievementDefinition(id: "hydration_hero", title: "Hydration Hero", description: "Meet your daily water goal.", iconName: "drop.fill", criteriaType: .waterGoalHitCount, criteriaValue: 1, pointsValue: 15),
            AchievementDefinition(id: "on_the_weigh", title: "On the Weigh", description: "Log your weight for the first time.", iconName: "scalemass.fill", criteriaType: .featureUsed, criteriaValue: 1, pointsValue: 10),
            AchievementDefinition(id: "first_5_lbs", title: "First 5 Pounds", description: "Lose (or gain) your first 5 lbs.", iconName: "figure.walk.motion", criteriaType: .weightChange, criteriaValue: 5, pointsValue: 50),
            AchievementDefinition(id: "target_reached", title: "Target Reached", description: "Reach your set target weight.", iconName: "flag.checkered", criteriaType: .targetWeightReached, criteriaValue: 1, pointsValue: 100),
            AchievementDefinition(id: "scanner_pro", title: "Scanner Pro", description: "Log a food item using the barcode scanner.", iconName: "barcode.viewfinder", criteriaType: .barcodeScanUsed, criteriaValue: 1, pointsValue: 20),
            AchievementDefinition(id: "ai_chef", title: "AI Chef", description: "Log a recipe generated by the AI Chatbot.", iconName: "brain.head.profile", criteriaType: .aiRecipeLogged, criteriaValue: 1, pointsValue: 25),
            AchievementDefinition(id: "picture_perfect", title: "Picture Perfect", description: "Log a food item using image recognition.", iconName: "camera.viewfinder", criteriaType: .imageScanUsed, criteriaValue: 1, pointsValue: 25),
            AchievementDefinition(id: "first_workout", title: "Ready For Anything", description: "Complete your first workout.", iconName: "timer", criteriaType: .workoutsLogged, criteriaValue: 1, pointsValue: 10),
            AchievementDefinition(id: "workout_streak_3", title: "Working Up a Sweat", description: "Complete 3 workouts.", iconName: "guage", criteriaType: .workoutsLogged, criteriaValue: 3, pointsValue: 20),
            AchievementDefinition(id: "workout_streak_7", title: "Building Up", description: "Complete 7 workouts.", iconName: "guage.badge.plus", criteriaType: .workoutsLogged, criteriaValue: 7, pointsValue: 30),
            AchievementDefinition(id: "workout_streak_15", title: "Forming A Routine", description: "Complete 15 workouts.", iconName: "speedometer", criteriaType: .workoutsLogged, criteriaValue: 15, pointsValue: 40),
            AchievementDefinition(id: "novice_chef", title: "Novice Chef", description: "Create a recipe.", iconName: "doc", criteriaType: .recipesCreated, criteriaValue: 1, pointsValue: 10),
            AchievementDefinition(id: "apprentice_chef", title: "Apprentice Chef", description: "Create 10 recipes", iconName: "arrow.up.doc", criteriaType: .recipesCreated, criteriaValue: 10, pointsValue: 20),
            AchievementDefinition(id: "adept_chef", title: "Adept Chef", description: "Create 20 recipes", iconName: "doc.text", criteriaType: .recipesCreated, criteriaValue: 20, pointsValue: 30),
            AchievementDefinition(id: "expert_chef", title: "Expert Chef", description: "Create 30 recipes", iconName: "doc.append", criteriaType: .recipesCreated, criteriaValue: 30, pointsValue: 40)
        ]
    }

    public static func level(for points: Int, thresholds: [Int] = defaultLevelThresholds) -> Int {
        var level = 1
        for (index, threshold) in thresholds.enumerated().reversed() where points >= threshold {
            level = index + 1
            break
        }
        return max(1, level)
    }

    public static func mergedStatuses(
        definitions: [AchievementDefinition],
        fetchedStatuses: [UserAchievementStatus]
    ) -> [String: UserAchievementStatus] {
        var statuses = Dictionary(uniqueKeysWithValues: definitions.map {
            ($0.id, UserAchievementStatus(achievementID: $0.id))
        })
        for status in fetchedStatuses {
            statuses[status.achievementID] = status
        }
        return statuses
    }

    public static func shouldCheck(
        _ achievementID: String,
        definitions: [AchievementDefinition],
        statuses: [String: UserAchievementStatus]
    ) -> Bool {
        guard definitions.contains(where: { $0.id == achievementID }) else { return false }
        return !(statuses[achievementID]?.isUnlocked ?? false)
    }

    public static func unlockedStatus(
        existingStatus: UserAchievementStatus?,
        definition: AchievementDefinition,
        date: Date = Date()
    ) -> UserAchievementStatus? {
        var status = existingStatus ?? UserAchievementStatus(id: definition.id, achievementID: definition.id)
        if status.id == nil { status.id = definition.id }
        guard !status.isUnlocked else { return nil }
        status.isUnlocked = true
        status.unlockedDate = date
        status.currentProgress = definition.criteriaValue
        status.lastProgressUpdate = date
        return status
    }

    public static func progressStatus(
        existingStatus: UserAchievementStatus?,
        definition: AchievementDefinition,
        progress: Double,
        date: Date = Date()
    ) -> UserAchievementStatus? {
        var status = existingStatus ?? UserAchievementStatus(id: definition.id, achievementID: definition.id)
        let capped = min(max(0, progress), definition.criteriaValue)
        guard abs(capped - status.currentProgress) > 0.01 else { return nil }
        status.currentProgress = capped
        status.lastProgressUpdate = date
        if status.id == nil { status.id = definition.id }
        return status
    }

    public static func evaluateDailyGoals(
        dailyLog: DailyLog,
        targets: DailyGoalTargets
    ) -> DailyGoalEvaluation {
        let macros = dailyLog.totalMacros()
        let calorieHit = targets.calorieGoal.map { abs(dailyLog.totalCalories() - $0) <= 100.0 } ?? false
        let proteinHit = abs(macros.protein - targets.protein) <= 10.0
        let carbsHit = abs(macros.carbs - targets.carbs) <= 20.0
        let fatsHit = abs(macros.fats - targets.fats) <= 5.0
        let hydrationHit = dailyLog.waterTracker.map { $0.totalOunces >= $0.goalOunces } ?? false
        return DailyGoalEvaluation(
            calorieHit: calorieHit,
            proteinHit: proteinHit,
            macroMasterHit: proteinHit && carbsHit && fatsHit,
            hydrationHit: hydrationHit
        )
    }

    public static func weightChangeProgress(initialWeight: Double, currentWeight: Double) -> Double {
        abs(currentWeight - initialWeight)
    }

    public static func hasReachedTargetWeight(
        currentWeight: Double,
        targetWeight: Double,
        tolerance: Double = 0.5
    ) -> Bool {
        abs(currentWeight - targetWeight) <= tolerance
    }

    public static func challengeAfterAddingProgress(
        _ challenge: Challenge,
        amount: Double
    ) -> Challenge {
        var updated = challenge
        updated.progress += amount
        if updated.progress >= updated.goal {
            updated.isCompleted = true
        }
        return updated
    }
    
    public static func potentialWeeklyChallenges(currentDate: Date) -> [Challenge] {
        let weekFromNow = currentDate.addingTimeInterval(7 * 24 * 60 * 60)
        
        return [
            Challenge(title: "Workout Warrior", description: "Log 3 separate workouts this week.", type: .workoutLogged, goal: 3, pointsValue: 75, expiresAt: weekFromNow),
            Challenge(title: "Protein Power", description: "Meet your daily protein goal 4 times.", type: .proteinGoalHit, goal: 4, pointsValue: 75, expiresAt: weekFromNow),
            Challenge(title: "Calorie Controller", description: "Stay within 100 calories of your goal for 3 days.", type: .calorieRange, goal: 3, pointsValue: 60, expiresAt: weekFromNow),
            Challenge(title: "Dedicated Dieter", description: "Log your food for all 7 days of the week.", type: .loggingStreak, goal: 7, pointsValue: 150, expiresAt: weekFromNow),
            Challenge(title: "Weekend Warrior", description: "Log at least one workout on Saturday or Sunday.", type: .workoutLogged, goal: 1, pointsValue: 40, expiresAt: weekFromNow),
            Challenge(title: "Five-a-Day", description: "Log at least 5 days in a row this week.", type: .loggingStreak, goal: 5, pointsValue: 100, expiresAt: weekFromNow),
            Challenge(title: "Macro-Minded", description: "Hit your protein goal 2 times in a row.", type: .proteinGoalHit, goal: 2, pointsValue: 50, expiresAt: weekFromNow),
            Challenge(title: "Active Start", description: "Log 2 workouts before Wednesday.", type: .workoutLogged, goal: 2, pointsValue: 50, expiresAt: weekFromNow)
        ]
    }
    
    public static var chefAchievementIDs: [String] {
        ["novice_chef", "apprentice_chef", "adept_chef", "expert_chef"]
    }
    
    public static var workoutAchievementIDs: [String] {
        ["first_workout", "workout_streak_3", "workout_streak_7", "workout_streak_15"]
    }
}
